// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nryaowcxkhrydiqnnlof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yeWFvd2N4a2hyeWRpcW5ubG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODQ1MDMsImV4cCI6MjA3MDk2MDUwM30.ccAgdlVWzsudZv0MipDmAc8ynFHjNlnOvAAkb8dv0M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});